# Generated by Django 4.1.2 on 2022-11-10 14:23

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]
    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_role', models.CharField(blank=True, choices=[('Administrateur', 'Administrateur'), ('Utilisateur', 'Utilisateur')], max_length=20)),
                ('poste', models.CharField(max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCategorie', models.CharField(blank=True, max_length=40, unique=True)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, verbose_name='nom')),
                ('prenom', models.CharField(max_length=40, verbose_name='prenom')),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin'), ('Societe', 'Societe')], max_length=40, verbose_name='genre')),
                ('telephone', models.IntegerField(verbose_name='telephone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('adresse', models.CharField(max_length=40, verbose_name='adresse')),
                ('profil', models.CharField(choices=[('Personne Morale', 'Personne Morale'), ('Personne Physique', 'Personne Physique')], max_length=20, verbose_name='profil')),
                ('profilS', models.CharField(blank=True, choices=[('*****', '*****'), ('PME', 'Petite Moyenne Entreprise'), ('PMI', 'Petite Moyenne Industrie')], max_length=20, verbose_name='profil societe')),
                ('date_rendez_vous', models.DateField(verbose_name='date rendez vous')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branche', models.CharField(default='vide', max_length=200)),
                ('categorie', models.CharField(default='vide', max_length=200)),
                ('clients', models.CharField(default='vide', max_length=200)),
                ('telephone', models.CharField(default='vide', max_length=100)),
                ('adresse', models.CharField(default='vide', max_length=70)),
                ('numero_police', models.CharField(default='vide', max_length=30)),
                ('date_effet', models.DateField(default='vide', max_length=20)),
                ('date_expiration', models.DateField(default='vide', max_length=20)),
                ('immatriculation', models.CharField(default='vide', max_length=150)),
                ('marque', models.CharField(default='vide', max_length=60)),
                ('prime_totale', models.BigIntegerField(default='vide')),
                ('apporteur', models.CharField(default='vide', max_length=50)),
                ('appelUn', models.BooleanField(default=False, verbose_name='Appel 1')),
                ('appelDeux', models.BooleanField(default=False, verbose_name='Appel 2')),
                ('appelTrois', models.BooleanField(default=False, verbose_name='Appel 3')),
            ],
            options={
                'db_table': 'account_relance',
            },
        ),
        migrations.CreateModel(
            name='Souscrire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('souscription', models.CharField(max_length=40, verbose_name='proposition')),
                ('prime', models.CharField(default='0', max_length=40, verbose_name='primes')),
                ('date_effet', models.DateField(blank=True, null=True, verbose_name='date effet')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name='date echeance')),
                ('date_emission', models.DateField(blank=True, null=True, verbose_name='date emission')),
                ('commentaires', models.TextField(default='aucun commentaires', max_length=150)),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account.client', verbose_name='client')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProduit', models.CharField(max_length=40, unique=True, verbose_name='nom produit')),
                ('categorie', models.ForeignKey(default='vide', on_delete=django.db.models.deletion.CASCADE, to='account.categorie', verbose_name='categorie')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomGrade', models.CharField(max_length=40, unique=True)),
                ('commentaires', models.TextField(max_length=150)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='nomGrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.grade'),
        ),
    ]
