# Generated by Django 4.1.2 on 2022-12-10 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscrire',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.produit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_role',
            field=models.CharField(blank=True, choices=[('Administrateur', 'Administrateur'), ('Commercial', 'Commercial')], max_length=20),
        ),
    ]
