# Generated by Django 3.1.2 on 2023-02-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_souscrire_produit_alter_user_is_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relance',
            name='appelDeux',
        ),
        migrations.RemoveField(
            model_name='relance',
            name='appelTrois',
        ),
        migrations.RemoveField(
            model_name='relance',
            name='appelUn',
        ),
        migrations.AddField(
            model_name='relance',
            name='ap1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relance',
            name='ap2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relance',
            name='ap3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relance',
            name='last_modified_ap1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relance',
            name='last_modified_ap2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relance',
            name='last_modified_ap3',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='souscrire',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
