# Generated by Django 3.1.2 on 2023-04-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230214_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_role',
            field=models.CharField(blank=True, choices=[('Administrateur', 'Administrateur'), ('Utilisateur', 'Utilisateur')], max_length=20),
        ),
    ]
