# Generated by Django 3.1.2 on 2023-04-17 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20230413_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nomGrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.grade'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.categorie', verbose_name='categorie'),
        ),
        migrations.AlterField(
            model_name='souscrire',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='account.client', verbose_name='client'),
        ),
    ]
